# Generated by Django 2.0.2 on 2018-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
